### ISSUE TITLE
feature: split kubestellar release into 'core' and 'plugins' to support helm and brew initiative

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1055]
### Feature Description

Our release has all ks core plugins and ks kubectl plugins in the same tar archive.  These should be split out to allow for helm install of core components on kind, kubernetes, openshift, and plugins to install the complimentary plugins from the matching kubestellar release for kubectl using brew.

### Proposed Solution

1) split kubestellar release (from make file) into 2 parts.  core and plugins

### Want to contribute?

- [x] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I think that we have been using the term "plugins" as a bit of a short-hand for something that is a little different. I think what is important is who/what needs to use which of the executables.

FYI, currently the unified build puts the following in `bin/`.

```
bash-3.2$ ls -1 bin
kubectl-kubestellar-deploy
kubectl-kubestellar-ensure-location
kubectl-kubestellar-ensure-wmw
kubectl-kubestellar-get_external_kubeconfig
kubectl-kubestellar-get_internal_kubeconfig
kubectl-kubestellar-get_log
kubectl-kubestellar-prep_for_cluster
kubectl-kubestellar-prep_for_syncer
kubectl-kubestellar-remove-location
kubectl-kubestellar-remove-wmw
kubectl-kubestellar-syncer_gen
kubectl-workspace-ensure
kubestellar
kubestellar-ensure-ca
kubestellar-ensure-kcp-server-creds
kubestellar-make-kcp-server-cert
kubestellar-version
kubestellar-where-resolver
mailbox-controller
placement-translator
remove-kubestellar
switch-domain
syncer
wait-and-switch-domain
```

If we focus on the case of deploying the core as kube workload (rather than bare processes) then those executables can be categorized as follows.

## Part of the core (used in the hosting cluster)

- kubestellar
- kubestellar-ensure-ca
- kubestellar-ensure-kcp-server-creds
- kubestellar-make-kcp-server-cert
- kubestellar-where-resolver
- mailbox-controller
- placement-translator
- switch-domain
- wait-and-switch-domain

## Used by a user to deploy the core

- kubectl-kubestellar-deploy

## Users by users of a deployed core

- kubectl-kubestellar-ensure-location
- kubectl-kubestellar-ensure-wmw
- kubectl-kubestellar-get_external_kubeconfig
- kubectl-kubestellar-get_internal_kubeconfig
- kubectl-kubestellar-prep_for_cluster
- kubectl-kubestellar-prep_for_syncer
- kubectl-kubestellar-remove-location
- kubectl-kubestellar-remove-wmw
- kubectl-kubestellar-syncer_gen
- kubectl-workspace-ensure

## Used by users of a deployed core AND useful to include in the core

- kubestellar-version

## Deployed in the WECs

- syncer

## Not used (only applicable for bare-process deployment)

- remove-kubestellar

**Comment by MikeSpreitzer** [comment]
In the case of deploying the core as bare processes, the categories "Part of the core" and "Used by a user to deploy the core" merge together and adopt the one executable from "Not used".

**Comment by MikeSpreitzer** [comment]
I could see lumping the categories above into two big baskets.

**executables needed in the core**, consisting of the categories
- Part of the core
- Used by users of a deployed core AND useful to include in the core

**executables needed outside the core**, consisting of the categories
- Used by a user to deploy the core
- Users by users of a deployed core
- Used by users of a deployed core AND useful to include in the core
- Only used with bare-process deployment

**Comment by MikeSpreitzer** [comment]
The next question is what does building look like and what gets built.  I can think of a few possibilities.

1. Both baskets go in `bin/` and there is a `make` target for each basket.
2. Each basket goes in a distinct binary directory (maybe `corebin/` and `bin/` ?) and `make build` covers both.
3. Each basket goes in a distinct binary directory _and_ has its own `make` target.
4. Each basket goes in a distinct binary directory _and_ has its own `make` target (`make corebuild`, `make userbuild`) and also `make build` invokes both of those.

**Comment by MikeSpreitzer** [comment]
This also raises questions of what happens to the quickstart and the bootstrap script.

**Comment by MikeSpreitzer** [comment]
There is some advantage in leaving the quickstart unchanged, and thus the usage of the bootstrap script unchanged.

This is not to deny a separate idea: give the bootstrap script the option to NOT defer to deployments already found on the `$PATH`. That makes sense orthogonally to this issue.

**Comment by MikeSpreitzer** [comment]
I think we need to make a deliberate choice about what happens with the quickstart.  I can think of a few possibilities.

(A) Keep the quickstart exactly the same. This means that both baskets of executables are delivered in one `bin/` for the user to add to their `$PATH`. I think the simplest way to get this done is to have release platform archives that have one `bin/` with both baskets of executables. To also support the brew thingy that installs just the executables needed outside the core, this means that for a release we create two archives per platform: one holding both baskets in one `bin/`, and one holding only the executables needed outside the core in `bin/`. I think the most direct way to do that is with two `make` targets: each puts the executables in `bin/`, and one builds only the executables needed outside the core and one that builds both baskets.

(B) Is like (A) but the two archives per (release, platform) correspond to the two baskets, and we modify the bootstrap script to fetch both and unpack the second one in a way that adds to the result of unpacking the first (which is normal for `tar`, right?).

(C) is like (B) except that the executables needed in the core go into `corebin/` while the executables needed outside the core still go into `bin/`. This means that the bootstrap script tells the user to add two KubeStellar directories to their `$PATH` rather than just one.

Approach (C) is the clearest in terms of making the distinction, but requires the most change to the quickstart and bootstrap script.

**Comment by MikeSpreitzer** [comment]
I think (A) might be least surprising to users.  Absent any other feedback, that is what I will do.

**Comment by MikeSpreitzer** [comment]
Since we are taking the approach of building an outside-only archive plus a full archive, the baskets that matter are the outside-only and the full. The difference is only the category of "Part of the core (used in the hosting cluster)", which is excluded from the outside-only basket.

**Comment by clubanderson** [comment]
@francostellari can you give this a review please?

**Comment by MikeSpreitzer** [comment]
oops, I approved the PR before I saw the request for more review.

**Comment by MikeSpreitzer** [comment]
More work could be done on this issue. Currently both flavors of release archive bundle `config/` and `core-helm-chart/` as well as `bin/`. The user flavor does not need `config/`.

**Comment by francostellari** [comment]
I personally do no like the idea of having some many different scripts. A lot of them could be assembled in higher level scripts, especially the plugins. Additionally all these changes may have breaking implications.
I think we need to focus on understanding on what needs to go into the future space manager based KS.
