### ISSUE TITLE
bug: kubestellar kubectl plugins should detect Kubestellar core version and avoid throw error if incompatible

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1058]
### Describe the bug

I am able to run any version of the kubestellar kubetl plugins against a kubestellar endpoint.  The problem is that not all versions of the plugins are compatible with all versions of the Kubestellar Core version running.  we need to put a mechanism in place to stop any incompatibility and notify the user.

### Steps To Reproduce

1. install kubectl kubestellar plugin v 0.6
2. run plugin against v0.7
3. weird behavior occurs

### Expected Behavior

error should be thrown to avoid confusion from user or misconfiguration.

**Comment by MikeSpreitzer** [comment]
Agreed. There is a non-trivial design issue here regarding what "compatible" means. We could strive for the utmost in accuracy, allowing any combination that will get what the user expects done. Thinking about all that entails scares me. I suspect the more practical approach is to define a more conservative check: success implies that what the user expects will get done, but failure does not guarantee that there would actually be a problem. But while I am willing to take some of that liberty in principle, the more we take in practice the less usable the resulting system will be. So there is some interesting design to do here.

To inform that design, I would like to understand what went wrong to prompt #1049 .

**Comment by clubanderson** [comment]
I'm happy with exact match between version of plugin and version of core. That's good enough for now. And if there is a mismatch, offer the plugin user the brew command to get the version they need. Simple. 

The bug I closed turned out to be scripts that were mismatched. I deleted anything and everything related to kubestellar in my path, and then pull v0.7.0 bin and then it worked again. To before I did that, I asked braulio to access the core from his laptop and he didn't have my issue. So that confirmed it for me. No reason to follow a flake, let's just try to get to parity and a suggestion if not parity.

**Comment by MikeSpreitzer** [comment]
It would be unsurprising, and thus probably not dissatisfying, to users for us to apply one [semantic version](https://semver.org/) to all of KS MCCM and do the checking based on that. To do that properly and achieve the behavior you desire, we would need to graduate from major version 0 to major version 2 (at first) and increment the major version again with any backward incompatible change. To avoid incrementing the major version unnecessarily, we would need to increment the minor version when needed and the patch version otherwise; this contrasts to current practice which makes only one release on each release branch.

To be clear, what we are versioning here is not just what is commonly considered "public API", but every aspect of the core that anything on a user's `$PATH` depends on (e.g., how many pods and containers appear in the host cluster and what are their names, when the core is deployed in a host cluster). That is not what "semantic versioning" is advertised to be used for, but nothing stops us from using it for that purpose and I think our doing so would be acceptable to users.

**Comment by MikeSpreitzer** [comment]
Also, we could stick with major version 0 for a while longer and treat every change in minor version as a backward incompatible change.

**Comment by clubanderson** [comment]
Just looking for simplicity here. If the plugin version does not match the core version, fail and give brew instructions for getting the right version of the plugin installed.

**Comment by MikeSpreitzer** [comment]
I am also looking for simplicity of implementation, as well as behavior that is as ordinary as we can easily arrange (for the sake of making it easy on users). After thinking a little more, a couple thoughts occur to me.

With #884 we should have changed the major version of the `edge.kubestellar.io` API group, from `v1alpha1` to `v2alpha1`. That is the ordinary thing to do when making a backward-incompatible change. I was a bit leery of doing that because it affects the whole API group. But we really are not planning any in-place rolling upgrades from 0.7 to 0.8, so I think it is fine to bump the major version on the whole API group. And since we have not tagged 0.8 yet, we still have time to make this right.

A Helm chart has a release number. We can use that to identify the version of the interface between the inside and the outside of the helm chart. Again, that is the ordinary thing to do.
