### ISSUE TITLE
feature: subscriptions (needed to install an OpenShift operator) should be an easy-to-configure option for edgeplacements/locations to include

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1066]
### Feature Description

We should figure out how to make support for subscriptions (operators) easy-to-configure for edgeplacements/locations - this is a common need for our customers (on openshift, not all platforms - so that is why I am saying shortcut - something we can switch on for the customer and do the lifting automatically for them underneath the covers)

### Proposed Solution

no sure what the solution should be.  I am including crd/subscriptions.operators.coreos.com, operatorgroup/operators.coreos.com, and crd/operatorgroups.operators.coreos.com alongside the edgeplacment when trying to install any operator on an OpenShift WEC.  That's the solution I am using.  Maybe the syncer has these objects installed by default?

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by pdettori** [comment]
Those seem the correct objects ( subscriptions.operators.coreos.com, operatorgroups.operators.coreos.com). However, based on the specific operand you may need other CRDs and VCRs. For example, for the Nvidia GPU operator, if you plan to automate also the install of a cluster policy you need also clusterpolicies.nvidia.com. You may have to check case by case which operand your operators is managing.

**Comment by clubanderson** [comment]
Yes, indeed, one needs to create the CRs to use an operator. This issue is solely focused on what it takes to install an operator subscription. If we can offer just that ability as something easy to configure/turn-on, that would lessen the load on our users.

**Comment by MikeSpreitzer** [comment]
We currently have an "easy button" for Kubernetes resources: the `--want-kube` command line flag on the `kubectl kubestellar ensure wmw` command (https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/commands/#creating-a-workload-management-workspace). It would be a small intellectual step to add a `--want-openshift` flag. I wonder, however: OpenShift adds a lot of stuff, so would we want to break it up into groups that can be added individually?

Also, the kind `Route` is now used in our user-quickstart-openshift, so that is needed immediately?
