### ISSUE TITLE
feature: Change name of WDS to PostOfficeSpace to help with user experience

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#1136]
### Feature Description

As a final step in the conversion to using edgeDeployment bundles, it would be great to make the name of the incoming workload to something that is more aligned with a customers perspective.  A mailbox is a place where people drop off mail and trust the mail will get to its intended location.  WDS (workload descriptor space) is not something a person knows the intent and must be taught/educated on what it is.  Now that the MBS is removed from KubeStellar, it is possible to use the "mailbox" name again in a more natural way - a user-facing place where customers drop off their workloads to be delivered to their intended location(s).

### Proposed Solution

change the name of the WDS to MBS (Mailbox Space)

- [ ] update installation
- [ ] update kubectl plugins
- [ ] update interfaces in WR, PT, MB controllers as needed
- [ ] update documentation

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
I think this is part of changing the design, so that we do not work with the same concepts. I am positively for using a different name for a different concept. BTW, in the neighborhood we have been using the term "mailbox" specifically to mean something that is in 1:1 correspondence with WEC. While the current MCAD workaround to the lack of #884 in release-0.7 is to use a WDS per WEC, that was never the general design.

**Comment by clubanderson** [comment]
changing title to "PostOffice" unless and until there are other ideas.
