### ISSUE TITLE
feature: have client-go code generation

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1537]
### Feature Description

in ks-0.20 branch, makefile doesn't include code generation for client-go informer/lister/etc.
all code is using dynamic client with unstructured objects instead.
it is preferred to have typed clients like we had in ks0.15 and use a dynamic client with unstructured only when there is no other option.

### Proposed Solution

implementation + tests

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer can you help with this?
I'm assuming you know this part best and could do it quickly.

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum : yes, I can start on it Tuesday. I expect I will start from what is in KubeStellar release 0.15 and then switch from kcp-special to regular tools, and probably remove the patching (which I suspect was there only for kcp-specific reasons).

@pdettori : where is WorkStatus defined?

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer sounds good. thank you.

**Comment by pdettori** [comment]
> @nirrozenbaum : yes, I can start on it Tuesday. I expect I will start from what is in KubeStellar release 0.15 and then switch from kcp-special to regular tools, and probably remove the patching (which I suspect was there only for kcp-specific reasons).
> 
> @pdettori : where is WorkStatus defined?

@MikeSpreitzer it is defined in the status-addon project in our internal GitHub, which we need to bring under https://github.com/kubestellar . We have also another issue here, there are incompatible dependencies between the libraries imported by the status-addon (from https://github.com/open-cluster-management-io/addon-framework ) and libraries we use in ks-0.20 (deep down the issue is about different and incompatible versions of the open telemetry agent). I could not find a way to resolve those conflicts with replace directives in the go.mod file, so for the time being  I have been using the dynamic client packages to avoid importing the status-add on project. We may need to think a better way for this, perhaps defining a separate project for all APIs we define that all projects can import without dragging along other dependencies that can be problematic, or have circular deps issues.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer The space-framework is already doing vanilla k8s code generation without any dependency on KCP. You can simply copy the generating script under hack and it should work as is (once you move the resource into its place)

**Comment by ezrasilvera** [comment]
Also note that the dependency on KCP is  coming implicitly through the inclusion of tools.go which pulls in go.mod with its replacements of k8s --> kcp version. 
In our go.mod we don't have KCP replacements and therefore it should use the regular k8s generators.
