### ISSUE TITLE
feature: rework the Key struct in the placement code (or equivalent for PlacementResolver)

### ISSUE THREAD

**Issue by vMaroon** [kubestellar/kubestellar#1703]
### Feature Description

The use of the Key struct in the PlacementResolver to identify objects is adding a lot of GVK <-> GVR conversion overhead, which:
- Complicates code
- Creates instances of erroring where can be avoided
- Introduces validation issues when these mappings go out of sync

Initially, the use of Key was for being as close as possible to the existing code (under some efficiency constraints), and a rework was planned for after initial merge.
During the review of #1681, @MikeSpreitzer repeatedly raised the point that things can be better if the resolver worked with resource instead of kind.

### Proposed Solution

Rework placement's Key or introduce a new one for the new PlacementResolver.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
More specifically, the issue is that centering the internal data structures on "kind" rather than "resource" is a mismatch with the most commonly used library fuctions --- the discovery and dynamic libraries are in terms of "resource".

However, centering the internal data structures on "resource" rather than "kind" will probably not completely remove the need for mapping between the two, because this is a fundamental pain point in Kubernetes. The representation of an API object uses "kind" rather than "resource".

**Comment by pdettori** [comment]
> The representation of an API object uses "kind" rather than "resource".

Yes. That was the motivation to use GVK as key for informers/listers. The idea was to do the GVR->GVK conversion only at informers creation time and then use the GVK (available in the object) when looking up the informer for the object. If the key is moved to be based on GVR, we need to convert GVK -> GVR for every update/create/delete of objects.
