### ISSUE TITLE
feature: add unit tests for transport controller

### ISSUE THREAD

**Issue by nirrozenbaum** [kubestellar/kubestellar#1704]
### Feature Description

current transport code do not include unit tests. we should add unit tests.

### Proposed Solution

need to implement unit tests for transport code.
In addition, new code should not be merged unless there is a unit tests to cover it. 

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer @ezrasilvera may we close this issue as done?

**Comment by MikeSpreitzer** [comment]
The unit test we have is for the generic part, not the OCM transport plugin nor both together. The unit test we have is very limited in what it can do, due to the very limited information in the Transport interface and the fact that the standard fake clientsets do not support LIST and WATCH well enough for informers to be able to react to changes (the test can only test the reaction to the initial state).
