### ISSUE TITLE
bug: confusing content in cmd/

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1750]
### Describe the bug

Normal usage is that each subdirectory of `cmd/` corresponds to an executable to build. Today we have two exceptions.
1. `cmd/client-options` has an expected-to-be-shared package. That would normally go in `pkg/`.  **Fixed**
2. `cmd/transport` is just a fragment of a transport controller. If I understand correctly, there could be multiple transport controllers, and each would be a distinct executable and each could use the fragment currently in `cmd/transport`. If I have that right then this is also something that would normally go in `pkg/`.### 

### Steps To Reproduce

See above

### Expected Behavior

Each subdirectory of `cmd/` corresponds to an executable to build.

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer thanks for opening this issue.
1. you are correct. client options doesn't belong to `cmd`, although I also feel it doesn't belong to `pkg`.
I've looked for something similar in k8s github and the closest example I could find is the following:
https://github.com/kubernetes/kubernetes/blob/5909bd2ddf9b4a4ee2c6507be7dc50d1920e5035/staging/src/k8s.io/controller-manager/options/generic.go
I think maybe we can put it under options dir. (so we have cmd, options, pkg). wdyt? 

2. In a running KS system, there are no multiple transport controllers, there is just one. The single transport controller is pluggable and in order to plug the specific implementation, I've put a function that gets the impl as arg and then runs the single controller.
This is not a fragment of the transport controller, **this is the only transport controller**. Whoever initializes this controller just need to supply the specific impl of the interface. 
there could be different plugins that initialize this controller with different implementations of the interface.
so about (2) I still believe this should reside in cmd.
I could find an example for such a controller in k8s github. maybe we can look for examples in other CNCF repos (like prometheus, etc..)

**Comment by nirrozenbaum** [comment]
btw, about point (2) - if you look in the base-controller.go file contents:
if we would rename Run function to main and remove the plugin injection, the code is a classic cmd file.

**Comment by MikeSpreitzer** [comment]
Regarding point (1). Putting shared command line stuff in an `options/` directory would be better than putting it in a subdirectory of `cmd/`. I think it would be even less surprising to put it in a subdirectory of `pkg/`. I looked in Kubernetes itself, and found no `options/` directory at the top level of any repo. https://github.com/kubernetes/kubernetes has none. For `kubectl` there is https://github.com/kubernetes/kubernetes/blob/master/cmd/kubectl/kubectl.go, which imports from `k8s.io/component-base` (which is a classic "util" style grab bag of stuff) and https://github.com/kubernetes/kubectl (which has a `pkg/` but no `options/`). For `kube-apiserver` there is a similar structure, importing https://github.com/kubernetes/apiserver . That has no top-level `options/`, it has command-line stuff under `pkg/`. The `k8s.io/component-base` repo is not structured like a typical project repository; it has neither `cmd/` nor `pkg/`. This particular repo is more like a shared utilities repo for use by other repos.

Regarding point (2): thanks for clarifying your intent. That clarification is worth putting into the architecture document. Since the plan is to have only one executable, it would indeed be ordinary to put the `func main` for that executable in `cmd/`. BTW, I would say the design a little differently. Or maybe I still do not understand your intent. If I understand it correctly, I would describe it with words like the following. The transport controller executable has all the transport plugins built in, and has a command-line flag that selects which plugin to use.

**Comment by MikeSpreitzer** [comment]
I have indeed been looking in base-controller.go, and that is what made me think that the design is a distinct executable per plugin. I see that the plugin has to be decided before the command line is parsed.

**Comment by MikeSpreitzer** [comment]
(1) has been resolved by #1751 

Regarding (2), I now understand that the design _is_ to have an executable per plugin, and there is no executable build from `ks/kubestellar/cmd/transport`. This at least requires a clear comment on the exceptional structure in that file or a `doc.go` of that package (the latter would be more of a winner if there were not such a strong tradition of putting no useful documentation in `doc.go`) or a README file in that package. And I think it would be better to have that package under `pkg/`.
