### ISSUE TITLE
feature:  Workload customization per WEC

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1897]
### Feature Description
In some cases when a workload is deployed to multiple WECs users may want to personalized the workload parameters for specific WEC(s)

### Current state description and problems involved
In general a user can achieve the above by:
1. Create a different workload object for each WEC
2. Create a binding policy that will send the workload to a specific WEC

While this may be good for some cases this is not a practical solution for several reason:
1. If we want to personalize cluster scope resources we need to use different WDS for each instance
2. Scalability issues: we basically duplicate the object on the WDS(s) which become impractical for large number of WECs
3. Manageability:  The user need to manage all those copies + the different binding policies. 

### Assumptions
1. For phase 1, we will be focusing on Hub based customization 
2. For phase 1 we will start with simple parameter substitution 

### Description
The user will specify a template with placeholders for fields that need to be personalized.  Once the target WEC is known KS will populate the placeholders with the WEC specific values.  

### Additional requirements
1. Some common fields should be pre-defined by KS (e.g., "wec-name" )
3. The should be able to add workload specific fields  (e.g., "debug-level")
4. Simple solution - if possible use existing mechanism or know syntax (e.g., Go templating) 
5. Very simple UX - user should easily define new fields and/or use existing pre-defined system fields.

**Comment by pdettori** [comment]
@ezrasilvera so the idea is to use something like go templating with variables expressed as "{{varName}}" in the yaml, right ? What is your thinking on how the per-WEC values of these variables would be defined ?

**Comment by ezrasilvera** [comment]
> @ezrasilvera so the idea is to use something like go templating with variables expressed as "{{varName}}" in the yaml, right ? What is your thinking on how the per-WEC values of these variables would be defined ?

Yes. 
Personally I think we will probably use configmaps to hold those values.  Some will be populated automatically by KS from values in the managedCluster object, but we probably should allow the user to define his own. I think there can be several other alternatives  (KS will search the values in a chain of places 1. user CM in the WDS 2.  global CM created by KS 3. managedCluster  special labels ....

But this is just initial thinking we should first:
1. Agree on the requirements
2. Brainstorm directions (starting with what Mike already proposed) 
3. Who ever own it need to come up with design doc that can be reviewed (addressing questions like you asked)
4. Implementation - PR
We can probably accomplish all of it in 1-2 weeks (depending on speed of agreements :-) ) , I assume design + implementation is 1W and reviews is another week

**Comment by vMaroon** [comment]
On the how the customization object or sub-object should be defined, and on the UX, I think the following should be considered:

With agreement to Ezra's additional requirements that involve supporting system provided dynamically evaluated keys, and user provided key-value pairs:

- At medium to high scale, it makes more sense to customize workloads for groups of clusters
    - This means customization object should specify cluster selectors (scalable UX)
        - It would still be relevant to target single clusters, **but probably not a large amount of clusters customized individually with user-provided key-value pairs**
- There are two main POVs to this matter:
    - Customization can be viewed as a set of “personalization rules” that set values per WECs, and user workloads can make use of these values (somewhat of a ConfigMap with cluster selectors style)
        - Knowledge flow: rules are defined -> user is aware of rules -> user utilizes rules
        - Limitations:
            - Having to bind workloads to clusters correctly adds fragility
            - Conflicts on WEC rules level
    - Customization is related to both the workload and the target WECs (somewhat of a BindingPolicy with key-value pairs style)
        - Knowledge flow: rules are defined alongside the workload (perhaps indirectly)
        - Limitations:
            - Conflicts are now on a higher dimension

**Comment by nirrozenbaum** [comment]
few points I would like to add on this topic:
1. Instead of inventing our own syntax are implementing templates from scratch, use [GoLang templates](https://golang.org/pkg/text/template/), which is widely used in CNCF and k8s eco system. 
2. The key value pairs are configuration values. Instead of putting labels and annotations on ManagedCluster objects, use ConfigMap per WEC in its dedicated namespace on ITS.

There are many advantages in using GoLang templates:
### Standardization
GoLang templates are widely used in CNCF projects and k8s eco system. Few examples:
* **Helm**, **Kustomize** and **KubeBuilder** use it extensively to generate k8s resources based on user-defined templates and values.
* **Prometheus Operator** uses it for generation Prometheus and Grafana configuration files based on custom configurations.
* **Istio** uses it for generation configuration files such as virtual services, gateways, and destination rlules based on user-defined configurations.
* **Argo CD** uses it to generate k8s manifests from declarative yaml files stored in Git repos.
### Security
Provides a built-in mechanisms to prevent common security vulnerabilities such as injection attacks. it automatically escapes output to prevent injections making KS more secure.
### Performance
it's optimized for performance and efficiency. it's been tested and optimized by Go team and the community, ensuring it performs well even with large and complex templates.


Overall, using GoLang templates provides a reliable, secure and efficient way to implement templating for YAML files, saving development time and effort while ensuring the quality and maintainability of KS.

**Comment by clubanderson** [comment]
I would prefer that we keep the name 'customization' for this feature and change the name of this issue accordingly.

**Comment by ezrasilvera** [comment]
> I would prefer that we keep the name 'customization' for this feature and change the name of this issue accordingly.

done

**Comment by MikeSpreitzer** [comment]
Yes, it is easy for our code to invoke the Go text template expander. I am more concerned about the user experience.

In the legacy work I deliberately chose syntax that is different from what is used in bash and in Helm charts so that users do not have to use escaping when using bash and/or Helm to get workload objects into a WDS. Yes, escaping can be done, but it is a burden on users to have to remember it and do it. It is tolerable when it is rare. I expect that using Helm, in particular, may be common. I expect that KubeStellar will be just a cog in a bigger machine, so the story of escaping does not end here.

The go template expander can not possibly be as efficient and secure as a simple parameter replacement mechanism.

**Comment by MikeSpreitzer** [comment]
For an example of what the go template expander does when there is a reference to an undefined parameter, see https://go.dev/play/p/c6KI_I4bbOx

**Comment by nirrozenbaum** [comment]
> For an example of what the go template expander does when there is a reference to an undefined parameter, see https://go.dev/play/p/c6KI_I4bbOx

maybe I missed the point, this example looks very good to me. 
if a user tries to use parameter that was not defined, he is getting an appropriate error.
sounds to me like the normal behavior and exactly what I would expect.
btw, the fact that some parameter wasn't defined for WEC1 doesn't mean it wasn't defined for WEC2. you're making over assumptions.

I'm also failing to see how is it simpler to request from users to learn a new syntax instead of using standards.
from reading the comments of the others, I'm not sure anyone else thinks implementing our own syntax is simpler.

**Comment by clubanderson** [comment]
<img width="533" alt="Screenshot 2024-03-14 at 12 04 12 PM" src="https://github.com/kubestellar/kubestellar/assets/407614/dcb17d04-cd53-4ec2-8f2c-a5041a920762">
an example of how Karmada uses overridepolicy as a post-manifest (late-binding) mechanism

**Comment by pdettori** [comment]
The override policy is a different way to "customize", not based on templating - almost like kustomize vs. helm. 
Seems like it is possible to do things like override or even remove labels and annotations as well. This would be actually another feature we may need along the way for use cases like integration with Argo Workflows / Kubeflow Pipelines V2 / Kueue, where there is no templating (objects are created by KFP for example) but there is a need to change spec fields (e.g. .spec.suspend from false to true) and remove labels (e.g. workflows.argoproj.io/phase ). I am still exploring these integrations, but so far this override policy approach seems would work nicely for those use cases (templating would not).

**Comment by nirrozenbaum** [comment]
I think these capabilities are complementary. 
one can use templates while other may use something similar to override policy

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum : exactly, that is the approach we took in the legacy KubeStellar.

**Comment by effi-ofer** [comment]
> I think these capabilities are complementary. one can use templates while other may use something similar to override policy

Got to leave something for phase 2.

**Comment by MikeSpreitzer** [comment]
Regarding the `error` that comes out in xxx: it has a lot of content that is noise in our use case. The string returned by `Error()` of that `error` is "template: yaml:5:11: executing "yaml" at <.Foobar>: can't evaluate field Foobar in type main.customizationConfig". Remember that in our case we are talking about applying substring replacement to each leaf string independently. In that error message, the parts `template: yaml:5`, `executing "yaml" at`, and `in type main.customizationConfig` are not helpful. And the part `can't evaluate field Foobar` is not the wording I would choose. We would want wording in terms of our own interface and abstractions, something like `no value provided for parameter "Foobar"`.

**Comment by nirrozenbaum** [comment]
In my opinion, the above doesn't justify implementing capabilities we can get for free using go templates.
you can always put in the error field of an object any text you define.

the discussion here is more conceptually - 
There is a standard for doing something. CNCF projects are using this standard and we're also part of CNCF.
Now the question is - 
should we be aligned with the standard other CNCF projects are using or invent something of our own? 
for me the answer is simple - definitely to be aligned with standards and with CNCF projects.

for me it's the same question as asking if we want to implement KS controllers in Go or in python.

I don't see the benefit from inventing something of our own. 
IMO, the fact you would choose different wording for returned errors is not a good enough reason not to use the standard, nor the need to escape characters.
I haven't seen anything that we want to do and cannot be done using the standard.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer @nirrozenbaum another aspect is future extendibility. If I understood correctly @MikeSpreitzer main point is that for our current limited usage developing our own expansion may be simpler, more efficient, and more secure. Putting aside the question whether those statements are correct or not, I'm wondering whether this will limit us if/when we do want to add more capabilities and enrich the possibilities for user inputs in the future. 
My concern is that we may eventually find ourselves developing a full blown go templating as more requirements are coming in.

**Comment by nirrozenbaum** [comment]
you put aside the question about the statements, but I actually think these are also important. 
go templates is developed by Go community in golang repo -  a repo with more than 2K contributors and almost 120K stars.
if you google it quickly you will find that go templates was designed and optimized for efficiency and security.
trying to develop templates of our own cannot compete with what Go templates supplies - there is a very big community behind it, which helps optimizing design, performance and security.
and that is even before talking about the flexibility it allows if we want to extend the customization capabilities in the future.

**Comment by MikeSpreitzer** [comment]
If you google modern lisp implementations you will also find that they are designed and optimized for efficiency. And yet they are still far from the efficiency of C.

The Linux kernel is also an open source project with many contributors. It is designed for security. And yet...

The opening comment of this issue asserts that we will do substring replacement. Go templating is much more than that.

A feature and syntax that is deliberately limited to substring replacement is just what you want if you want to leave room for something more general later.

**Comment by MikeSpreitzer** [comment]
I think that overall we need to keep three degrees of customization in mind:
1. simple substring replacements
2. a collection of replace-this-with-that statements
3. Playing nice with other ecosystem players that do general templating (e.g., Helm charts, kustomize)

**Comment by clubanderson** [comment]
Customization should be late binding (after manifest work is created) to allow for environment-specific assignment of values, integrations with something like zookeeper and other k/v config stores (tikv), and allow for future service discovery whereby deployments can interact with each other without needing to call home to KS for configuration.

**Comment by MikeSpreitzer** [comment]
@clubanderson : each ManifestWork is destined to one specific WEC, so I do not see why customization has to be done _after_ the ManifestWork is created.

I _do_ see that doing customization in the WEC is an idea that KubeStellar must support. I do _not_ see that KubeSteller must _require_ **all** the customization to be done in the WEC.

**Comment by MikeSpreitzer** [comment]
My point about three degrees of customization is on this point. We want KubeStellar to play nice with other tools in the ecosystem, and we want users to be able to use powerful techniques like Go templating and Jinja templating. Since there are already other tools in the ecosystem that do these, my inclination is to lean on them. What they are missing is the 1:many distribution between clusters. For users that can get all their needs met by some other tool(s) doing customization post-distribution in the WEC, nothing is needed from KubeStellar. But I do not think this covers every user's needs. For these users we need KubeStellar to do rule-based customization as an integral part of its 1:many distribution.

**Comment by clubanderson** [comment]
@MikeSpreitzer please study karmada

**Comment by MikeSpreitzer** [comment]
@clubanderson : I saw your example in https://github.com/kubestellar/kubestellar/issues/1897#issuecomment-1997806942 . In that example the customization is not parameterized; each replacement is a string literal.

**Comment by MikeSpreitzer** [comment]
@clubanderson, regarding the idea that customization should be after manifest work is created. As shown in https://karmada.io/docs/core-concepts/concepts/ and explained in https://karmada.io/docs/core-concepts/architecture , Karmada produces its work objects in two steps: the first step creates a ResourceBinding object per (workload object, destination) and the second step applies the relevant overrides to each ResourceBinding to create a work object per (workload object, destination). So in fact, Karmada is doing its customization _prior_ to the existence of its work object. I think this is not the only possible choice, but it is the choice that Karmada makes.

**Comment by MikeSpreitzer** [comment]
@clubanderson, regarding service discovery in Karmada. I suppose you are referring to what is described at https://karmada.io/docs/userguide/service/multi-cluster-service . I do not suppose you mean that very directly, it is specifically about Service objects. I suppose you are suggesting that somehow information about each WEC might propagate from that WEC to the core, to be used in customization. I think that is something that makes sense to include as a possible source of parameter values. This also raises the question of why customization using those parameters would be done in the core rather than in the WEC. There are possible answers, such as the user wants to be able to write one layer of customization that takes input from both core and WEC rather than write two distinct and non-interacting layers of customization.

**Comment by MikeSpreitzer** [comment]
FYI, I have drafted a change to #1760 to make it use golang text/template instead of parameter expansion. It is the last commit in branch https://github.com/MikeSpreitzer/kcp-edge-mc/tree/templatize

**Comment by MikeSpreitzer** [comment]
In a parameter based paradigm, we can easily allow any Kubernetes label or annotation name as a valid parameter name. With Go language templating, the names have to be valid Go language identifiers.
