### ISSUE TITLE
feature: Custom  WEC-oblivious object transformation

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#1976]
## Description of current state
Currently KS supports two modes of "manipulating" the objects that are deployed into the WEC:
1. Filtering:
    * Is done per resource types 
    * Is done only for pre-defined Kube native resources (E.g., services)
    * Execute the exact pre-defined operation on the field (E.g., remove, set specific value, etc..)
2. Parameter expansion: Simple parameter substitution
    * Currently is done per WEC retrieving the same value for all objects deployed to that WEC
   
## Requirements
In several use cases the above mechanisms are not flexible enough. Some examples:
1. Filtering for CRDs - some workloads require filtering for their CRDs, supporting that with the current approach is not practical.  (E.g., Argo Workflow)
2. Different filtering for objects of the same KIND (e.g., per selection criteria) 
3. Different operations/filtering depending on the workload deployed (even for Kube resources)
4. Be able to easily define complex operations (replace fields, set values, remove fields, etc..) 

## Proposal
Staged approach to gradually cover the above requirements:

### Phase 1
1. Start with something that binds to workload objects only in terms of the "kind" or "resource" of the object, not more fine-grained.
   - Allow for backwards-compatible extension in the future to more fine-grained binding. Here "backwards-compatible" means that old clients get what they expect even when using the extended API and new implementation.
2. Start with something that only describes removal of parts of the workload object.
   - Allow for backwards-compatible extension in the future to allow other transformations on the workload object.

### Future phases
1. Allow the user to perform other operations than just removal (e.g., adding and updating fields)  
2. Allow the user to define selection criteria on which objects the operation will apply and not just according to KIND

**Comment by pdettori** [comment]
Example of specific requirements for the Argo Workflows and Kubeflow Pipelines use case:

- Filtering (or changing value) for the `.spec.suspend` field
- Filtering for specific labels:
  `workflows.argoproj.io/completed`
  `workflows.argoproj.io/phase`
  `pipeline/runid`

**Comment by MikeSpreitzer** [comment]
Terminology: "filtering" is a poor choice when you mean something more general (which indeed you have asserted). For that reason we have taken to saying "cleaning" rather than "filtering".

While I support the more general terminology, so that we do not have to do a bunch of rewriting if and when we want to do something more general, I have not yet seen a demonstrated need for anything other than removing content.

I also have not seen a demonstrated need to treat different objects of a given kind differently, in a given WDS.

**Comment by MikeSpreitzer** [comment]
I have considered defining something based on `kustomize`. I think that it would handle the specific use cases cited so far, but it has a weakness.

That weakness arises because of the fondness in Kubernetes API object design for representing what is logically a map as a list of objects with certain field(s) defined to hold the key of the logical map. An example is the Containers array in a PodSpec; the name field of the Container object is the key in the logical map.

The problem with kustomize is that I have not found an effective way to deal with such common map representations. I considered https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_patchesjson6902_ , but https://datatracker.ietf.org/doc/html/rfc6902 defines a "path" to be "a JSON-Pointer value
   [[RFC6901](https://datatracker.ietf.org/doc/html/rfc6901)]" --- and JSON-Pointer can not say "pick the array member whose `name` field is 'controller'".

I also considered https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_patchesstrategicmerge_ . When run by a kube apiserver that knows the schema of the object type --- and thus knows which fields are keys --- this can do the job. But it would be more problematic when kustomize is being invoked by one of our controllers.

Another down-side of kustomize is that it is defined as a transformation on YAML. A controller using it would have to render the object into YAML, then kustomize, then parse the YAML again. This is do-able but costly.

**Comment by MikeSpreitzer** [comment]
Here is an outline of a simple proposal that I think would fit the needs shown so far.

Defined a Kind of object that specifies a set of JSON-Path identifying content to remove. One object per Kind of workload object. Restrict the expressions in the JSON Paths to conjunction of field-equals-literal.

**Comment by MikeSpreitzer** [comment]
The most intricate case that I know about now is the `spec.suspend` field of Job objects. Whether it should be removed or not depends on the usage scenario. So far we only have actual usage that requires removal. I suspect that, at worst, this aspect of usage may vary between installations of KubeStellar or, at most, between WDSes --- not between Job objects in one WDS.

**Comment by pdettori** [comment]
@MikeSpreitzer we have also a use case for integration with KubeFlow Pipelines that I pointed out in https://github.com/kubestellar/kubestellar/issues/1976#issuecomment-2026194844

**Comment by pdettori** [comment]
But I agree that so far the two use cases we have are about removing either a specific field or specific labels for all objects of a specified kind  before being delivered to a WEC.

**Comment by MikeSpreitzer** [comment]
There is also another possible approach, which was the aspiration in the legacy design. That approach uses a denaturing proxy to make a denatured view of the WDS available to clients. A client that accesses a WDS through this view gets to use objects without the normal (_for that WDS_) behavior attaching to them.

**Comment by ezrasilvera** [comment]
@pdettori @MikeSpreitzer I think it's a mistake to go with a limited solution that basically just clean objects before they go to the WEC.  I thought that the solution we are looking for should also handle substitution, adding fields, etc...
I also strongly recommend not to hardcode it according to KIND, but to allow a general selector. What happen if someone want to clean/set fields according to the WEC to which they are sent ? 
@pdettori I thought that the same mechanism should also take care of manipulating the object before it is placed on the WDS,  (e.g., helping put the suspend to TRUE) ,  otherwise we would need to have two different mechanisms that basically doing the same thing but at a different time of the object lifecycle. I think that at least the definition mechanism should be the same.

**Comment by effi-ofer** [comment]
Have we considered using the term 'transformation' rather than 'cleaning' ?

**Comment by MikeSpreitzer** [comment]
I think that we agreed on the following requirements.

- Start with something that binds to workload objects only in terms of the "kind" or "resource" of the object, not more fine-grained.
- Allow for backwards-compatible extension in the future to more fine-grained binding. Here "backwards-compatible" means that old clients get what they expect even when using the extended API and new implementation.
- Start with something that only describes removal of parts of the workload object.
- Allow for backwards-compatible extension in the future to allow other transformations on the workload object.

**Comment by MikeSpreitzer** [comment]
We did not explicitly discuss but I would like to add this requirement:

- The way(s) that a part of a workload object can be identified includes working with the Kubernetes penchant for representing what is logically a map by what is concretely a list of struct/record/object. That is, allows picking out one particular entry in this logical-map-but-actually-list.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer I updated the issue description. I think your PR/proposal should cover Phase 1

**Comment by MikeSpreitzer** [comment]
I would like to clarify what I mean by "client" in that definition of "backward compatible", because it occurs to me that a reader might take it either of two ways: (1) a client of the kube apiservers, doing any of the CRUDLW operations on CustomTransformation objects that the apiservers offer, or (2) a client of the custom transformation service, creating CustomTransformation objects and writing their desired state and reading their reported state (as if there were any). I mean (2).

**Comment by MikeSpreitzer** [comment]
Here are some forseeable use patterns for needing to work with a map represented by a list of records.

- Admission control or controller adds an environment variable (to a PodSpec) that needs to be removed.
- Admission control or controller adds a volume (to a PodSpec) that needs to be removed.
- Admission control or controller adds a sidecar container that needs to be removed.

**Comment by MikeSpreitzer** [comment]
Here is another user story, from @shmuelk . He wants a headless Service. That is specified by including `clusterIP: "none"` in the Spec. He needs KubeStellar to _not_ remove that field on the way to the WEC.

**Comment by ezrasilvera** [comment]
@MikeSpreitzer @pdettori While this is larger than  #2060 , I think we agreed that currently there is no need/use-case for larger scope transformation.  Should we close it ?

**Comment by pdettori** [comment]
@ezrasilvera  I vote to close it. We can always open specific feature requests in the future if the use cases for those arise.
