### ISSUE TITLE
feature: Combined status from multiple WECs

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#2017]
Support getting workload status when deploying to multiple WECs.  The user should be able to define what should be returned and if/how to summarize it.

There are few modes that seems important:
1. Direct copy: Copy the statuses from all wecs into WDS. This is probably reasonable only for a small number of WECs
2. Selected fields: Copy the statues from all WECs but only for selected filed(s) 
3. Apply some summarization operator over the statuses from all WECs

(Summarization is a subitem of this feature)

A design proposal from @vMaroon :
https://docs.google.com/document/d/1kkJsdX7hfUzLl88i5t-i_Tcn30wDjOeM

A design proposal from @MikeSpreitzer : #2055

**Comment by vMaroon** [comment]
@ezrasilvera can we move this to high priority?

**Comment by pdettori** [comment]
This feature might be helpful for the Argo CD integration. A summary object may be shown in the application graph to get aggregate information about status of deployments on the WECs. I expect also this to be valuable for getting aggregate status of the deployment of the stack in the data pre-processing use case that @clubanderson has been working on.

**Comment by shmuelk** [comment]
The "admin web app" I mentioned is part of an application that we are working on that uses KS. It makes it easier for users to work with our application.

**Comment by ezrasilvera** [comment]
Moving to high priority due to @shmuelk input.

**Comment by MikeSpreitzer** [comment]
See #567 for a proposal for the legacy system.

**Comment by MikeSpreitzer** [comment]
I do not want to forget about scale. I think that what gets returned into the WDS needs to be something that "fits" into the WDS. There are a few things that can reduce status volume to fit into the WDS:

- use aggregation functions with constant-size outputs (like the ones in SQL). For a non-example: set union is technically an aggregation function, but its output is not constant sized.
- use what is called "projection" in relational algebra (and appears after the keyword "SELECT" in SQL) to filter the content of each workload object.
- cap the size of accumulated lists/sets. This can be practical when the concern is looking for objects "in trouble" because of bugs; in this usage it suffices to find a few WECs that exhibit the bug(s).

I think that if a user (client) wants to see the full reported state of a given object from every WEC AND the number of WEC may be large then we need to have an interface that does not require making a copy of all that data in the WDS.

**Comment by pdettori** [comment]
Since there are many possible features we could offer here, it would be helpful to have more specific requirements for the known use cases - @shmuelk would you have an example of how a summarized status would look like for your use case ?

**Comment by vMaroon** [comment]
## Phased Approach Outline
This major feature will be implemented in a phased approach of three essential (mandatory) and two extension PRs. After the mandatory phase:
- The feature will be functional and usable by users
- The feature will be fully documented and tested

### Essential PRs Phase
Implementing the functionality of the feature is split into three stages:
1. Declaring new API resources and API documentation: this part only declares the user-spec portion of the API
  - Issue: #2138
2. Implementing the calculation of user-spec API declared in (1)
  - Issue: #2140
3. Calculating and generating combined-status (CombinedStatus) objects
  - Issue: #2141 
4 + 5: TODO

**Comment by ezrasilvera** [comment]
Tracking this feature with https://github.com/kubestellar/kubestellar/issues/2143  - closing this one
