### ISSUE TITLE
bug: No deletion of workload object status on deletion of workstatus

### ISSUE THREAD

**Issue by waltforme** [kubestellar/kubestellar#2020]
### Describe the bug

Status of workload objects in WDSes are not deleted, when corresponding WorkStatus objects are deleted due to BindingPolicy selection changes on singleton status report WEC(s).

I ran into this bug when I'm writing tests to my code changes for #1945.

### Steps To Reproduce

1. Run Kubestellar into a state where a WorkStatus object exists and the singleton status is reported to the corresponding workload object. One way to do that is leveraging the "singleton status testing" part of the ginkgo e2e tests.
2. Delete the WorkStatus object by changing the WEC selection. To do this, change the bindingpolicy's `clusterSelectors`, so that the `clusterSelectors` doesn't cover any WECs. Another way is to change the labels of the WECs so that they are not selected by the bindingpolicy any more.
3. Observe the deletion of the the WorkStatus object and the unexpected, continuous existence of the workload object status.

### Expected Behavior

Status of workload objects in WDSes should be deleted when corresponding WorkStatus objects are deleted.

### Additional Context

Currently the status controller just do nothing on deletion of WorkStatus object.
https://github.com/kubestellar/kubestellar/blob/189107031c2c2792aebad35128c0fd7b2abd2191/pkg/status/controller.go#L280-L283

More importantly, a _reference_ to WorkStatus object, instead of a full object, gets queued in the workqueue of the status controller. So when a WorkStatus object is deleted, the information to track the corresponding workload object (in .spec) is not visible to the workers.

Therefore, to fix this one, I think we need to change the current structure of the status controller quite a bit.

**Comment by waltforme** [comment]
As mentioned in the opening comment, I'm working on #1945 and I wrote unit tests for my code changes against #1945. But this bug prevents the unit tests from succeeding. Therefore, I have to leave the unit tests in an incomplete state. I will complete the units after this bug is fixed.

**Comment by MikeSpreitzer** [comment]
While the baseline design for a particular kind of Kubernetes API object is that it is the interface to a microservice, with clients writing the `.spec` and the service writing the `.status`, that is not always the case. While handling the general case may be another issue, we might want to pay attention to one aspect when working on the issue at hand. That is, multiple parties can write into the `.status` of an object. Some of those parties might be in the WEC while others write to the copy in the WDS.

Also, note that --- in terms of the content passed from apiserver to client --- the shape of the `.status` can vary over time (e.g., due to fields that are omitted from YAML or JSON if empty, or due to maps whose key set changes). For examples that I have actually seen, see https://github.com/kubernetes/api/blob/v0.28.11/apps/v1/types.go#L497-L505 . So the status controller might write `.status.unavailableReplicas` at one point in time, and at the next point in time the WorkStatus will contain `.status.availableReplicas` and not `.status.unavailableReplicas`. Just doing a positive write will leave both `.status.unavailableReplicas` and `.status.availableReplicas` in the workload object.

BTW, remember that `.metadata.managedFields` lists all the fields that exist and were last written by each FieldManager.
