### ISSUE TITLE
"cluster" should be "clusters" in the Quick Start section (grammatical error)

### ISSUE THREAD

**Issue by JonathanWentaoBao** [kubestellar/kubestellar#2309]
### Describe the bug

In the Install Software Prerequisites section of the Quick Start page, the description under the bash cmd at the top of the section mentions "three Kubernetes cluster", where "cluster" should be "clusters" (to reflect the multiplicity), shown in the picture below:
![vsip issue](https://github.com/kubestellar/kubestellar/assets/171893847/1dfc413c-f3a9-4d89-a189-9e8015aeba8d)

### Steps To Reproduce

1. go to kubernetes.io documentation
2. navigate to quick start page
3. scroll down to the the Install Software Prerequisites section until you see the bash command at the top of the section
4. scroll down to the descriptive paragraph beneath the bash command

### Expected Behavior

"three Kubernetes cluster" should instead read as "three Kubernetes clusters"

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by clubanderson** [comment]
@JonathanWentaoBao please PR this.

/assign @JonathanWentaoBao

**Comment by MikeSpreitzer** [comment]
@JonathanWentaoBao: If I understand correctly, you resolved this issue with PR #2313 . If so then you should close this issue. FYI, GitHub would have done that automatically for you if you had completed the line `Fixes #` in the PR's opening comment.

OTOH, you may opine that this issue is not resolved until the fix has been published in a release. If so then you should add some progress tracking into this issue, so that the progress can be readily seen here.

**Comment by clubanderson** [comment]
@JonathanWentaoBao I think this was resolved in the latest unreleased development version of the documentation - can you please check and close this issue if it is resolved. Thank you.

**Comment by JonathanWentaoBao** [comment]
closing issue
