### ISSUE TITLE
bug: "|| true" can be removed to prevent redundancy

### ISSUE THREAD

**Issue by JonathanWentaoBao** [kubestellar/kubestellar#2314]
### Describe the bug

In the Core Helm Chart section of kubestellar documentation, under the "Kubeconfig files and contexts for Control Planes" section, there is a block of code that explains how to add a context to the current kubeconfig file and make it the current context. In this block, "|| true" can be removed to avoid redundancy since this process no longer takes place within the local shell.
![helm issue](https://github.com/kubestellar/kubestellar/assets/171893847/2b362795-c996-4181-a977-1ca01457d4b0)

### Steps To Reproduce

1. go to kubestellar.io documentation (unreleased version)
2. navigate to the Setup tab
3. go to the Core Helm Chart page
4. scroll down past the "Kubeconfig files and contexts for Control Planes" section until you see the subsection titled "Using kflex CLI"
5. the issue should be in the code block directly under it

### Expected Behavior

the first line of the block should read as "kubectl config delete-context $cpname" instead of "kubectl config delete-context $cpname || true"

### Want to contribute?

- [X] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
FYI, the critical thing is not "takes place within the local shell" but rather whether the shell has `set -e` (AKA `set -o errexit`). We used to recommend that in our web pages because some people would copy-and-paste a block of commands and some before the last would fail and the user would not notice. I suspect that the recommendation to `set -e` got accidentally rubbed off without explicit consideration in the recent flurry of website editing.

**Comment by clubanderson** [comment]
@JonathanWentaoBao - not certain, but I think this was resolved in the latest unreleased development version of the documentation - can you please check and close this issue if it is resolved. Thank you.
