### ISSUE TITLE
feature: Enable KubeStellar to work with OpenZiti

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#519]
### Feature Description

I would like to see KubeStellar integrated with OpenZiti as an option in the Zero-Trust project space.  

### Proposed Solution

There are 2 options available.
 - Tunneling
 - Transport library replacement in KCP and KubeStellar-Syncer

The preferred option, for now, is transport library replacement.

Question: Is there an option to use OpenZiti in a sidecar?

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment]
on hold - waiting for OpenZiti to re-engage in the future

**Comment by clubanderson** [comment]
Hear from Ken this afternoon. He is ready to continue @MikeSpreitzer

**Comment by qrkourier** [comment]
Yes, I tested the tunneling approach by patching the worker clusters' manifests with a Ziti sidecar. This gave them access to the KCP API via Ziti with a pod level transparent proxy sidecar.

Next, I'll test a variation on the tunneling theme by deploying a proxy at the cluster level. Andy mentioned this would probably be useful in the short term. The main hurdle is KCP server TLS verification by the workers. I need to learn how to configure the KCP server certificate's DNS SANs. 

Further steps could include patching the worker cluster agent with the Ziti library to obviate the proxy. 

An optimization on the sidecar approach is to patch the Go program that generates the worker cluster manifests so that it optionally provides a proxy as a sidecar or cluster service.

**Comment by clubanderson** [comment]
@MikeSpreitzer @ezrasilvera @pdettori how is this effort affected by the Space framework abstraction?

**Comment by clubanderson** [comment]
Met with OpenZiti at KubeCon NA.  Architectural discussions continue - working to choose the right path forward.
