### ISSUE TITLE
bug: update all doc instances of 'pcluster' to 'workload execution cluster'

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#552]
### Describe the bug

we are using the term pcluster throughout our documentation and we agreed that this term no longer serves us well.  It is not in our dictionary for the project either.

### Steps To Reproduce

rtfms

### Expected Behavior

update 'pcluster' to something like 'workload cluster'

**Comment by clubanderson** [comment]
@ezrasilvera @pdettori @yana1205

**Comment by francostellari** [comment]
@clubanderson what about "target cluster(s)"

**Comment by clubanderson** [comment]
'workload execution cluster'? 'target cluster'? 'workload target' (and expand in glossary)

can we come up with a name that is sans 'cluster'

review multicluster SIG terminology (other communities) to align (+3)(-1)

new issue: glossary needed (+2)

use 'edge cluster' instead of pcluster? 'workload execution'

what do we say instead of workspace? 'logical cluster'?  'logical apiserver'?

**Comment by clubanderson** [comment]
will revisit on next community call to close out

**Comment by MikeSpreitzer** [comment]
The title of this issue just begins to tug on the ball of string...

- We agreed many months ago that "pcluster" is a TMC term and in edge-mc the analogous term is "edge-cluster".  Any usage of "pcluster" should have been changed to "edge cluster" months ago.
- Now that we are generalizing beyond edge to general multi-cluster management, "edge" is no longer the right adjective to identify the clusters in question.  Using "managed" instead of "edge" would align exactly with OCM terminology, which I think would be great because we really do mean the same thing.  However, other suggestions have been made.  One is "workload".  IMHO that is too close to the existing term "workload management workspace" or, even more confusingly, "workload management logical cluster".  To make the distinction clear, we need to simultaneously rename "workload management workspace" to something that compares and contrasts nicely with whatever we rename "edge cluster" to.  I propose to use the adjective "workload description" in the WMW replacement and "workload execution cluster" as the replacement for "edge cluster".
- We have to replace "workspace" in our terminology and might as well do all the renaming in one swell foop.  We have generally been using "logical cluster".  This has the advantage of being the term that kcp uses for their realization of the concept.  This is a boon for familiarity, but also a bust for clarity; using the same term for our abstraction obscures the fact it is an _abstraction_ with multiple concrete realizations.  It is also confusing because it includes the word "cluster", which leads people to think we are talking about things that have worker nodes and run workload --- which we distinctly do NOT mean.  It is also particularly confusing in our context of multi-cluster management.  People may not clearly see that the logical clusters and the managed clusters are distinct things.

**Comment by MikeSpreitzer** [comment]
As far as I can tell, the least bad replacement that I can recommend for "workspace" is "logical apiserver".  I am not happy with the fact that this term is longer in both the writing and the speaking (eight syllables!).  But I have not been able to think of a better alternative yet.  I like the focus on the apiserver, because I think that really is the focus of the concept we are trying to convey --- the behavior that a client gets when interacting with an apiserver.  I think this logically includes the behavior of the associated controllers that are generic (related to API machinery) but not the controllers that are specific to the management of containerized workloads.  And of course it includes the behavior of persistently storing the API objects.

With that as the primary change, I recommend to rename our concepts as follows.

- "edge cluster" becomes "workload execution cluster"
- "workload management workspace" becomes "workload description logical apiserver"
- "inventory management workspace" becomes "inventory logial apiserver"
- "mailbox workspace" becomes "mailbox logial apiserver"
- "edge service provider workslpace" becomes "KubeStellar logical apiserver"

**Comment by ezrasilvera** [comment]
@MikeSpreitzer while I tend to agree with "logical apiserver" the resulting names seem to be very long now. For example "workload description logical apiserver"  seems too long.  
Do we need to add the logical apiserver to each of them ? 
"KubeStellar logical apiserver"  are we sure we will have only one?  If not maybe "KubeStellar  mgt logical apiserver"?

**Comment by ezrasilvera** [comment]
what about virtcluster ?  instead of "logical apiserver" ? I actually like the apiserver in the name as we require "apiserver behavior ", but we should try thinking on shorter name

**Comment by ezrasilvera** [comment]
E.g., "workload description virtcluster" ?

**Comment by MikeSpreitzer** [comment]
I find "virtual cluster" (or its contraction to "virtcluster") to share the same problems as "logical cluster".

I am not happy with the fact that "logical apiserver" is longer than "workspace" and longer than "logical cluster" in both the writing and the speaking (eight syllables!). But I have not been able to think of a better alternative.  The good news is that we have already fallen into the habit of using acronyms.  So we will almost always be writing WEC, WDLA, ILA, MBLA, and KSLA.  I think that makes it tolerable.

**Comment by MikeSpreitzer** [comment]
When written out, "logical apiserver" is only two characters longer than "logical cluster" and, as it is just part of longer terms, I think that difference is negligible.  When abbreviated, LA is just as short as LC.

**Comment by MikeSpreitzer** [comment]
A possible alternative to "logical apiserver" is "space".  That would give us the following renamings.

- "edge cluster" becomes "workload execution cluster"
- "workload management workspace" becomes "workload description space"
- "inventory management workspace" becomes "inventory space"
- "mailbox workspace" becomes "mailbox space"
- "edge service provider workspace" becomes "KubeStellar implementation space"

**Comment by MikeSpreitzer** [comment]
I should also add for the ESPW replacement:
- `KubeStellar provider <new term for workspace>` (small change from ESPW)

**Comment by MikeSpreitzer** [comment]
We have decided on https://github.com/kubestellar/kubestellar/issues/552#issuecomment-1612471611 modulo the question of what to say in place of "edge service provider".

**Comment by MikeSpreitzer** [comment]
We have decided to replace "edge service provider workspace (ESPW)" with "KubeStellar core space (KCS)".

**Comment by clubanderson** [comment]
I replaced a good number of the in 'main' documentation.  Can we identify a list of what other places are impacted by the change of 'pcluster' to 'workload execution cluster' (WEC)?  We don't need to make changes now, but we should take inventory of what remains.  Could this be as simple as a 'search and replace' in a single PR?

**Comment by nirrozenbaum** [comment]
quick `pcluster` search in your favorite IDEs shows there are no more instances of this term anywhere.
this issue can be closed @clubanderson .

**Comment by clubanderson** [comment]
Almost true. I believe there is still pcluster in the output of prep-for-cluster. I think I put this in another issue. So maybe this issue can be closed if the other issue is opened and being cared for separately.
