### ISSUE TITLE
bug: need working RHEL pre-reqs

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#602]
### Describe the bug

pre-reqs for RHEL are a mirror of ubuntu right now - and I think that will not work.

### Steps To Reproduce

1. go to our quickstart - kubestellar.io/quickstart
2. read the list of pre-reqs for RHEL
3. try to run them

### Expected Behavior

working pre-req instructions for RHEL

**Comment by clubanderson** [comment]
@KPRoche since you are digging around in this area, can you take this?

**Comment by KPRoche** [comment]
Yes, although my "RHEL" environment is actually CentOS. They're both Fedora, so it should work, as nothing in the current instructions appears to be specifically RHEL-only

**Comment by clubanderson** [comment]
you can feel free to change the title on the tab to be "Fedora/RHEL" or "Fedora"

**Comment by dvbnrg** [comment]
I am also testing on Fedora and I seem to be running in to an issue on the first step:

`
< KubeStellar bootstrap started >----------------
< Ensure kcp is installed >----------------------
which: no kcp in 
kcp not found in the PATH.
Downloading kcp+plugins v0.11.0 linux/amd64...
Installing kcp+plugins into '/home/justdave/Dev/kcp'...
Add kcp folder to the PATH: export PATH="/home/justdave/Dev/kcp/bin:$PATH"
< Ensure kcp is running >-----------------------
Running kcp... logfile=/home/justdave/Dev/kcp_log.txt
Waiting for kcp to be ready... it may take a while
`
I'm currently waiting for a few minutes before stopping the execution of the command.

**Comment by clubanderson** [comment]
/assign @francostellari 
/assign @MikeSpreitzer 
/assign @KPRoche 

Mike, Kevin, and Franco, can you have a quick look?

**Comment by KPRoche** [comment]
> I am also testing on Fedora and I seem to be running in to an issue on the first step:
> 
> I'm running the following command:
> .
>.
>.
> Waiting for kcp to be ready... it may take a while
> 
> ` I'm currently waiting for a few minutes before stopping the execution of the command. I have yet to see this command proceed past waiting for kcp to be ready

That exact problem happened to me on a Raspberry Pi running CentOS stream!

Examination of the _kcp_log.txt_ file revealed that starting kcp had failed because I had microshift running, and it had already appropriated the port that kcp wanted. The start of kcp failed, and the bootstrap didn't detect that fact and exit.

I solved the problem and successfully started KubeStellar on my Raspberry Pi just by stopping microshift (systemctl stop microshift) before executing the commands to start KubeStellar.

Check to see if you have openshift running, or something else grabbing the needed port. The bootstrap for the quickstart makes some assumptions about default available resources. If it's not the port, the log file should tell you what prevented kcp starting properly.

if you are executing the startup command from the kubestellar directory, that's where _kcp_log.txt_ should be written.

**Comment by dvbnrg** [comment]
Here are the last 5 lines from my log files:

`I0703 21:18:41.037382  138447 virtual.go:118] "starting virtual workspace apiserver" component="kcp" component="kcp"

I0703 21:18:41.037607  138447 dynamic_serving_content.go:113] "Loaded a new cert/key pair" name="serving-cert::/home/justdave/Dev/.kcp/apiserver.crt::/home/justdave/Dev/.kcp/apiserver.key"

W0703 21:18:41.037677  138447 authentication.go:47] Authentication is disabled

I0703 21:18:41.057881  138447 store.go:1501] "Monitoring resource count at path" resource="customresourcedefinitions.apiextensions.k8s.io" path="<storage-prefix>//apiextensions.k8s.io/customresourcedefinitions"

W0703 21:18:41.058387  138447 genericapiserver.go:586] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.

Error: cannot create the 'admin.kubeconfig' file with an empty token for the shard-admin user`

**Comment by clubanderson** [comment]
@dvbnrg i would try running the cleanup steps at the bottom of the document first before trying again. This, to me, sounds like there is a version of KCP left behind from your previous install. If you run the cleanup steps it will remove remnants and you can start from scratch.

**Comment by dvbnrg** [comment]
removing all the artifacts, freeing up my ports, and rerunning the install command I get the following error:

`
Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:2379: connect: connection refused"
6263   │ W0704 20:02:49.100877   31351 logging.go:59] [core] [Channel #190 SubChannel #191] grpc: addrConn.createTransport failed to connect to {
6264   │   "Addr": "localhost:2379",
6265   │   "ServerName": "localhost",
6266   │   "Attributes": null,
6267   │   "BalancerAttributes": null,
6268   │   "Type": 0,
6269   │   "Metadata": null
6270   │ }. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:2379: connect: connection refused"
6271   │ I0704 20:02:49.148398   31351 genericapiserver.go:539] [graceful-termination] apiserver is exiting
`

**Comment by clubanderson** [comment]
@KPRoche can you help @dvbnrg get over the line here?

**Comment by KPRoche** [comment]
> removing all the artifacts (rm -rf ~/.kcp and kcp/ as well as the kcp_log.txt), freeing up my ports, and rerunning the install command I get the following error:
> 
> `Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:2379: connect: connection refused" 6263 │ W0704 20:02:49.100877 31351 logging.go:59] [core] [Channel #190 SubChannel #191] grpc: addrConn.createTransport failed to connect to { 6264 │ "Addr": "localhost:2379", 6265 │ "ServerName": "localhost", 6266 │ "Attributes": null, 6267 │ "BalancerAttributes": null, 6268 │ "Type": 0, 6269 │ "Metadata": null 6270 │ }. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:2379: connect: connection refused" 6271 │ I0704 20:02:49.148398 31351 genericapiserver.go:539] [graceful-termination] apiserver is exiting`

Everything I've found so far says those errors are most frequently symptoms of a corrupted etcd in kubernetes. 
What version of kubectl do you have installed? I believe kcp is sensitive to that, correct @clubanderson ?

**Comment by dvbnrg** [comment]
I have Client Version: v1.25.9-dispatcher of kubectl installed and I was running etcd via brew. However, during the installation process, I disabled it. Should I remove etcd and try again?

**Comment by MikeSpreitzer** [comment]
Folks, you need to be paying attention to running processes as well as what is in the filesystem.

Remember that you can look at what ports are being listened at with `netstat -lnt` on Linux systems.  You can use `ps` to find processes.  You can use `lsof -nP` to list both together.

I typically do the following command to look for relevant processes.

```bash
ps axlw | egrep 'kcp|mail|placem|sched|where|go-build'
```

**Comment by MikeSpreitzer** [comment]
@KPRoche : I am surprised by your comments about shutting down microshift on your rpi.  Isn't that what you are using as your edge cluster?  Are you using your rpi to run the center components?

**Comment by MikeSpreitzer** [comment]
@dvbnrg : just to be clear, we are talking here about the pre-reqs in the quickstart, not some other doc, right?

**Comment by KPRoche** [comment]
@MikeSpreitzer : That is my ultimate goal, yes. 
However, to fix the Fedora-family commands in the pre-reqs, I needed to be able to try all the steps in the quickstart.md; that entailed temporarily stopping microshift so I could test the bootstrap script to launch KubeStellar and confirm it actually would start on my CentOS machine.

Eventually I will get back to attempting to run KubeStellar on my Ubuntu VM and the execution cluster on the rPi.

**Comment by MikeSpreitzer** [comment]
This issue illustrates another problem with our documentation: we need to tell people how to make a good trouble report.  I think that will include the following things.

1. Include `-X` on the bootstrap command line
2. Return a complete typescript and copies of the logs.

**Comment by MikeSpreitzer** [comment]
This is also telling me that the "check all preconditions" code should include checking that the relevant TCP ports are NOT currently in use.

**Comment by KPRoche** [comment]
@dvbnrg did you manage to get your quickstart running?
I noticed yesterday that after PR 733, the list of pre-reqs has grown. yq and ko were added, which weren't there when I started debugging the Fedora-family commands.
yq can be installed via snap

**Comment by clubanderson** [comment]
@KPRoche can this be closed?

**Comment by KPRoche** [comment]
@clubanderson Oops! newbie mistake. Yes, I think so.
