### ISSUE TITLE
Feedback on website - Documentation Improvements

### ISSUE THREAD

**Issue by ronenkat** [kubestellar/kubestellar#632]
1. The website can have more motivation and use-cases. For example, the goals in the website are collaborative goals (how we are building Kubnestellar), and not Kubestellar (as a software) goals.
1. There is an assumption of understanding and knowing prior terms and definitions such as KCP, workspaces, etc. Would. be good to either have a reference or documentation.
1. The quick-start is very technical and "do that, do this" with no explanation of what is being done, how, and how it reflects in Kubestellar. The extended example provides more context to each stage.
   * more information on the context of the YAMLs would be good, for example `EdgePlacement.yaml` 
   * In step (d) the reference to `edge-placement-c` in the text seems wrong or not explained well.
1. A primer on the underlaying concepts of Kubestellar would be nice to read.

**Comment by clubanderson** [comment]
@ronenkat thank you for your feedback.  We had similar feedback from @aslom re: having a glossary.  Maybe it is time to take this as a priority.

**Comment by clubanderson** [comment]
@amanroa can you please take a closer look at this issue and see if you can come up with plan to tackle the items Ronen has listed?

**Comment by MikeSpreitzer** [comment]
Regarding the current home page, https://github.com/kcp-dev/edge-mc/blob/f4d99eee6d9030b5b7a6951da0c3504657abb6c7/docs/content/index.md :

- I think modularity is critical, and since we seem to be intending the term "KubeStellar" to cover multiple user-distinguishable modules of functionality, that should be crystal clear right up front.
- I currently see two modules: the original multi-cluster configuration management module, and the logical cluster abstraction layer.
- The current home page starts with a listing of features that has features drawn from both modules without distinction.  I think this needs to be revised so that the top-level structure is a list of modules, and inside the section for each module can be a list of most exciting features and other important features.

**Comment by amanroa** [comment]
@ronenkat could you elaborate further on part 1 of your feedback? Specifically, what is the difference between software goals vs collaborative goals?

**Comment by amanroa** [comment]
Because I'm not sure about part 1, I'll provide feedback on parts 2-4. I also have some of my own feedback regarding the webpage. 

2.  Adding a glossary page with terms + succinct definitions would be great for new users to get background knowledge (I really support this idea). This could also be a way to solve part 4, by adding a section before/after the terms and definitions describing the concepts that Kubestellar is based on.

3. I definitely agree that we could add more detail to the Quickstart so that users have some concept of what the commands are actually doing in the background, however, I would caution against adding _too much_ depth. The Quickstart is there for a reason, to get the user setup with Kubestellar very quickly. On the other hand, the extended example is for those users who want more information on the processes occurring in the background while they are setting up Kubestellar. So I would say that we should add more detail - for example, at the `edge-placement-c` that was mentioned - but be careful not to basically replicate the extended-example.  

4. As stated in part 2, we could add this primer to the end of the glossary, or we could make it its own page. However, I think we should try to not overcrowd the header at the top of the site. This could be solved by (again) just combining the primer and glossary, or doing a sort of drop down where the tab visible in the header is titled 'Background Information', and clicking on it makes a dropdown appear with links to the 'Glossary' and 'Primer' (these don’t have to be the actual names). 

Some other notes that I had when looking at the website are: 

Could we make the left menu titles bigger and/or expand the page so that there isn’t space between the sidebar and the content (I noticed this on the new home page, specifically) ? Because there was so much space there that I didn’t actually notice the sidebar until I was looking for a way to try to get to the README. maybe just increasing the font size will solve this issue without having to reformat the whole site by increasing the content box size.

Also, the Quickstart and Getting Started tabs at the top lead to the same pages, so I propose that we remove one (probably the Quickstart tab) for sake of simplicity.

**Comment by clubanderson** [comment]
I like the removal of the tab, I think that would help the 'funnel' tremendously.  All the points above are moving in the right direction, imo.

**Comment by ronenkat** [comment]
> @ronenkat could you elaborate further on part 1 of your feedback? Specifically, what is the difference between software goals vs collaborative goals?

The goals on the website sounds like a plan, i.e., milestones (collaborate, define, validate) instead of goals like a provide a virtual workspace to manage multiple clusters, etc...
Generally it read like a project proposal.

**Comment by MikeSpreitzer** [comment]
Regarding @ronenkat 's item 3: #415 attempted to add some explanatory material, but not too much.  You mgith find that interesting.

**Comment by MikeSpreitzer** [comment]
Regarding @ronenkat 's item 1: it seems to be about the README (https://docs.kubestellar.io/main/readme/) rather than the landing page (https://docs.kubestellar.io/main/).  I have some related comments on the README in #180 .  I would say that what Ronen observed about the existing "Goals" text is that it has statements about our process rather than statements about what the process is inteded to produce.

**Comment by amanroa** [comment]
Thanks for the detail about part 1. I agree that it doesn’t really state anywhere in the README about what actually comes out of running KubeStellar. So we could either a) remove and rewrite that section to be more technical, b) have two sections: for example, ‘[KubeStellar’s] Objective’ for the overall plan (the stuff currently in the ‘Goals’ section), and ‘What KubeStellar Creates/Produces/Builds etc…’ . 

I also took a look at #415 . It seems pretty interesting, and I can see the benefit that it can add to the QS. Reading it certainly makes the QS make more sense. However, I do see that adding too much detail could just make it similar to the extended example. To find a happy medium between this, I noticed that there were a few instances in that issue where you were explaining definitions for terms such as ESPW, IMW, WMW, etc. If we create a Glossary, we could tweak the edits in #415 to remove the terms/definitions and make it a bit more streamlined, since those terms would be defined in the glossary anyways. Just a thought!

**Comment by eaepstein** [comment]
_On the other hand, the extended example is for those users who want more information on the processes occurring in the background while they are setting up Kubestellar._

The extended example is quite informative and I think well written, but intended for developers. Most users will first want to know how to implement their own scenario of interest. User documentation should focus on the things that users need to and/or can specify. A required functionality missing entirely is a mechanism to configure "summarization", noted in the extended example as being aspirational.

**Comment by eaepstein** [comment]
A couple more comments on documentation. First, I second Ronen's initial comment in this issue. My words in a note to Andy were: "QuickStart is a set of seemingly black magic commands without any overview that would help a new user know what is going on."

Second, user facing documentation that describes how to use the product under development is essential to guide implementation. In my experience, writing the [basic] users guide after the fact exposed many poor design choices that could have been easily avoided.

**Comment by MikeSpreitzer** [comment]
The example1 document was originally written by me as an aspirational illustration of what we were trying to develop, as a document for us developers.  It includes an example that is a little (not much) more elaborate than the one in the quickstart.  The use of example1 has shifted over time.  I agree that users need something that is not exactly what example1 is.  I see users as needing:
- a quickstart that teaches what is going on in that scenario;
- a more extended scenario to exercise the platform more, while teaching what is going on;
- documentation of how the platform may be used in the full generality that we are promoting.

**Comment by ezrasilvera** [comment]
As I wrote on our slack - I think we have excellent documentation for someone who wants to try out KubeStellar (examples, QS, etc..) 
I think we need to add another high level layer of documentation that is aimed towards users who just want to understand what is KubeStellar without the need to go through any example, installation, etc.  These users are divided into k8s experts and people without k8s knowledge, so the docs should have both levels. 
This should include, for example: 
1. High level architecture diagram (the only one I found is buried in Mike's example 
2. Detailed architecture explanation of major components 
3. Clear definition of the unique goals (preferably something which other don't provide)
4. Short description of  use-case examples at very high level that illustrate capabilities (can be synthetic use case). Should not require prior knowledge  (e.g., what is NVI, what is Kyverno, etc..)

**Comment by amanroa** [comment]
Coming back to the 'glossary' idea that was proposed earlier. Could this glossary/KubeStellar primer be placed in the User Guide? Right now, that page doesn't seem to have anything that is being worked on and I think that having high level definitions of the terms used throughout the webpage could be useful. Additionally, we could use the User Guide as a way to generally explain the underlying concepts of KubeStellar, as @ronenkat stated earlier.

**Comment by amanroa** [comment]
I've created a PR with an initial glossary at #807. Some terms I felt were a little unclear, so they don't have any definitions/they have a shorter definition. If anyone would like to add comments to my PR to help me develop the glossary, that would be greatly appreciated!

**Comment by clubanderson** [comment]
@amanroa can you incorporate some more of the terms in the initial description from @ronenkat - item 2 - "There is an assumption of understanding and knowing prior terms and definitions such as KCP, workspaces, etc. Would. be good to either have a reference or documentation." This will help finish off the initial work needed for the glossary.  You can review this work with @ronenkat to see if there is anything else he might suggest to be added.
