### ISSUE TITLE
feature: AAA support for KubeStellar

### ISSUE THREAD

**Issue by clubanderson** [kubestellar/kubestellar#711]
### Feature Description

Authentication, Authorization, and Accounting are not currently implemented in KubeStellar.  MCAD is requesting support for this.

### Proposed Solution

- [ ] Introduce AAA support in KubeStellar
- [ ] create a tutorial on how to use it.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
KubeStellar uses standard Kubernetes mechanisms for AAA.

**Comment by z103cb** [comment]
Yes, we need this !

**Comment by clubanderson** [comment]
@MikeSpreitzer can you expand on your comment to see if this is an acceptable answer for @z103cb ?

**Comment by MikeSpreitzer** [comment]
https://ibm-research.slack.com/archives/C05EK28MYJ1/p1688059961691769?thread_ts=1688054427.563179&cid=C05EK28MYJ1

**Comment by clubanderson** [comment]
Ok @MikeSpreitzer i understand now. Will wait for more info from Hai!

**Comment by MikeSpreitzer** [comment]
Also: some details about authorization appear in the following places.

(I am citing specific commits so that the content does not change out from under me, but to see these nicely rendered you would go to the corresponding page on the website --- which we edit a lot.)

- https://github.com/kubestellar/kubestellar/blob/v0.3.0/docs/content/Coding%20Milestones/PoC2023q1/mailbox-controller.md#usage
- https://github.com/kubestellar/kubestellar/blob/v0.3.0/docs/content/Coding%20Milestones/PoC2023q1/placement-translator.md#usage
- https://github.com/kubestellar/kubestellar/blob/v0.3.0/docs/content/Coding%20Milestones/PoC2023q1/kubestellar-scheduler.md should have an anlogous section but does not (I think?  @waltforme ?)
- https://github.com/kubestellar/kubestellar/blob/v0.3.0/docs/content/Coding%20Milestones/PoC2023q1/commands.md

**Comment by huang195** [comment]
First, I'm not very familiar with either Kubesteller nor MCAD. The following is my understanding after reading the documentation so far. Kubesteller is derived from KCP, and it allows one to specify how a workload is to be deployed to one or more k8s clusters. It has a k8s-like control plane for users to specify workloads and k8s clusters. Syncers are deployed to these k8s clusters that all listen to the Kubesteller controller and deploy resources when a resource placement decision has been made. These syncers are also responsible for summarizing status from deployed resources and reporting back to the Kubesteller controller.

MCAD team is planning to use Kubesteller to deploy MCAD components across multiple k8s clusters. This includes the the MCAD dispatcher, agents, and Prometheus for collecting metrics information. Once MCAD is deployed, users can deploy jobs by creating AppWrappers that are subsequently picked up the MCAD dispatcher, and from the resource information that it collects from its agents on each K8s cluster, it can make scheduling decisions on these jobs. If not enough resources are available, it will queue the jobs until resources become available later. It schedules jobs to K8s clusters by creating workloads in Kubesteller and binding them to specific k8s clusters. 

The AAA support mentioned in this issue is for the MCAD team to use Kubesteller to specify authentication and authorization policies so that only MCAD components are allowed to talk to one another, and no other workloads are allowed to talk to them (maybe this also applies to MCAD jobs too?) In Kubernetes, authorization policy is usually handled by the underlying CNI in the form of Kubernetes NetworkPolicy. Some CNIs even support higher level NetworkPolicies as CRDs. The NetworkPolicy objects can be created by the MCAD team and deployed via Kubesteller. However, the difficulty here is that the NetworkPolicy objects are only enforced within a single cluster, and for cross-cluster communication (which MCAD uses), you will need something like Clusterlink or a service mesh (Istio, Cilium).

Authentication on the other hand (mTLS) is usually not handled by the platform itself but are handled at the application level. However, if one is already using a service mesh like Istio or Cilium, the service mesh could handle this on behalf of the application. This usually involves obtaining X509 certificates signed by a local CA, and writing application logic to make use of those certificates to authenticate with peers and creating encrypted data channel via mTLS. We're trying to make this easier for the MCC team by creating a common service that provides certificate signing and certificate injection into workloads automatically. We're planning to use SPIFFE/SPIRE under the covers.

In our workstream, we're trying to create common services such as these so other teams could deploy their platforms/tools/workloads in a more secure manner (aka Zero Trust). Besides MCAD, I believe Kubesteller team could also benefit from these services deploying its components across multiple clouds/clusters.

I'm not clear about the Accounting aspect. Is the MCAD team asking Kubesteller to provide a view about available resources in each of the K8s clusters?

**Comment by waltforme** [comment]
>     * https://github.com/kubestellar/kubestellar/blob/v0.3.0/docs/content/Coding%20Milestones/PoC2023q1/kubestellar-scheduler.md should have an anlogous section but does not (I think?  @waltforme ?)

I see the point. Let me address this. Thanks @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
I would say that what you talked about the CNI typically doing is network-level filtering, while Kube has its own API-level authorization (RBAC being the most commonly exercised module for that).  Indeed Kubernetes has a kind of object to prescribe network-level filtering, NetworkPolicy, but it is not very expressive for talking about things beyond the scope of the containing cluster.  Other projects do networking for a bigger picture.  Am I correct in guessing that this is not what you mean to focus on?

Standard interfaces are great for separation of concerns.  SPIFFE provides a standard way for a workload to request its credentials.  That separates the concerns of (a) making the workload use SPIFFE to get its credentials at the right times from (b) all the concerns around providing those credentials.  I think it would make sense for the KubeStellar processes to be able to get their credentials through SPIFFE.  On the other side: thus far we have not fixed much around how those processes are run.  We have scripts that just run the KS processes using binaries that we build and publish, but those scripts are examples not limits.  The KS processes are plain go programs that a consuming project can build and package and deliver and run in any way desired.  We are starting work on containerizing those processes.

We are thinking about revising and extending our concept of inventory, noting that we are working with projects that need additional information in the inventory.  We are not sure what approach to take.  We note that SIG multi-cluster tried defining a standard for inventory and decided that a better approach is to not standardize that.

**Comment by huang195** [comment]
> Standard interfaces are great for separation of concerns. SPIFFE provides a standard way for a workload to request its credentials. That separates the concerns of (a) making the workload use SPIFFE to get its credentials at the right times from (b) all the concerns around providing those credentials. I think it would make sense for the KubeStellar processes to be able to get their credentials through SPIFFE. On the other side: thus far we have not fixed much around how those processes are run. We have scripts that just run the KS processes using binaries that we build and publish, but those scripts are examples not limits. The KS processes are plain go programs that a consuming project can build and package and deliver and run in any way desired. We are starting work on containerizing those processes.

That makes sense. I'm in discussion with Mariusz regarding how to create identity-as-a-service with SPIRE as the backend, initially used to enable Zero Trust, but could be re-used for other purposes. The challenge is how to make a clean boundary for separation of concern, so it is the easiest for developers to make use of such services. We can talk more about this with Mariusz when he's back next week.

**Comment by MikeSpreitzer** [comment]
NetworkPolicy objects control IP addresses and transport protocol & port.  Implementations query the kube-apiserver to map label queries over pods to the corresponding (IP addresses, protocol, port) sets.

BTW, do you consider using NetworkPolicy with pod label queries to be an example of zero trust?

**Comment by huang195** [comment]
Yes, that is how NetworkPolicy works under the cover. From user's point of view, it provides a mean for them to specify workloads by their attributes and dictate how workloads are allowed and not allowed to communicate with one another. This is the Authorization part of Zero Trust. The Authentication and Data encryption part of Zero Trust is done by mTLS, facilitated by SPIRE.

**Comment by MikeSpreitzer** [comment]
The authorization by (IP address, protocol, port) that is configured by NetworkPolicy objects and controllers does not connect to identities established in TLS; it relies on the kube control plane relating the NetworkPolicy's namespaceSelector && podSelector to IP addresses.

**Comment by huang195** [comment]
That's correct. There's no way to specify an identity by their TLS name (either CN or SAN in the certificate) in NetworkPolicy.  However, since SPIRE assigns identities by pod labels and NetworkPolicy can select identities by pod labels, pod labels can be used as the common thread between authentication and authorization. 

Once certs/keys are obtained from SPIRE, workload will either need to be modified to make use of them to establish mTLS for authentication and data encryption, or rely on service mesh such as Istio. It will be nice to be able to make use of the SPIFFE ID encoded in the certs to specify authorization policies, but as indicated above, that is not possible to do in NetworkPolicy.

**Comment by MikeSpreitzer** [comment]
The components in KubeStellar interact through API objects rather than request/response messages over the network, so a service mesh is beside the point.

**Comment by MikeSpreitzer** [comment]
There are also a couple of issues that are still to be addressed in KubeStellar.  One is that it flagrantly violates the principle of least privilege: the controllers get the root credentials and use them for some things.  Another is that we plan to switch from kcp APIExport&APIBinding to kube-bind, which entails some changes wrt authentication and authorization.  Today kube-bind uses OIDC and requires user interaction to do a binding.  I hope we can generalize that in the future.

**Comment by z103cb** [comment]
> I'm not clear about the Accounting aspect. Is the MCAD team asking Kubesteller to provide a view about available resources in each of the K8s clusters?
Yes, MCAD needs to understand if there are available resources on the agent clusters so that appwrappers are to be dispatched unto one of those clusters. The interaction between MCAD / kubestelar / Agent clusters to access the metrics needs to be secure (i.e MCAD as client needs to be authorised and authenticated to pull those metrics)>. 

MCAD will need to be updated to authenticate to get those metrics.

**Comment by z103cb** [comment]
![MCAD KStellar Integration](https://github.com/kubestellar/kubestellar/assets/109964136/78443f07-20da-4141-aae3-3b3b2366ebc9)

In my mind there are two places where AAA comes into picture (the red arrows in the diagram above):
* creating AppWrappers and getting updates to app wrappers state. MCAD relies solely on the state of the app wrappers to make decisions. So MCAD will need to be authenticated and authorised to access WMW (which in my understanding where app wrappers are created and their  status is updated). This might be just as simple as K8s RBAC. We just need to confirm.
* Reading remote cluster resource state from a metrics store (Thanos ?)

**Comment by huang195** [comment]
OK, this is more clear what the requirements are. There are 2 layers of access control: at the network layer, and at the application layer. We're talking about the access control at the application layer in this issue. Various components, including Kubesteller's own controllers and syncers and MCAD components, need to talk to Kubesteller apiservers to communicate with one another via various api objects. It's imperative that the access to these api objects are authenticated and authorized. RBAC seems to be a mature and natural solution to this problem. However, there are some details to be hammered out.

When MCAD talks to the kubsteller apiservers, it needs to be authenticated first. In my conversation with Mike, he pointed out that using x509 certs is one of the supported ways to do authentication. In the (m)TLS handshake, when the certs are exchanged, the Common Name field from the cert is extracted as the `user` and the Organization field as the `group` in the use of RBAC subsequently. So, whatever you're using to generate the certificates need to be mindful of these little contracts. Also, when signing your certificates, you want to make sure it is either signed by a CA also trusted by Kubesteller, or signed by Kubesteller's root or intermediate CA. 

I think this is where SPIRE is super useful, as it does all these certificate management tasks for you. In addition to x509 certs, it also supports JWT tokens. If we deploy SPIRE as a substrate service, any workload that runs will get its identity (in form of a certificate or a token) pretty much for free. We should coordinate this work going forward to minimize most of the AAA related works to the underlying platform substrates if possible.

**Comment by waltforme** [comment]
> Also: some details about authorization appear in the following places.
>     * https://github.com/kubestellar/kubestellar/blob/v0.3.0/docs/content/Coding%20Milestones/PoC2023q1/kubestellar-scheduler.md should have an analogous section but does not (I think?  @waltforme ?)

I had PR #774 trying to address this. Would you help to review? @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
Getting this right for MCAD is
/priority important-soon

**Comment by clubanderson** [comment]
@MikeSpreitzer it was explained to us by @z103cb that the communication path used for transmitting spec and status is acceptable for their needs. The path for transmitting metrics, for which Kubestellar is not a part of, is not fully defined and may require additional AAA coverage when it is. This is not a direct KubeStellar concern and is therefore not a critical priority for us at this time. Of course this may change if we somehow get in the business of shuttling metrics outside of an api server pathway in the future, but it is not our concern for phase 1 or phase 2 this year. Therefore I am removing the critical label. This issue is open to catch the requirements as they are identified, and thus far those requirements are not our direct concern in KubeStellar.
