### ISSUE TITLE
What does the space framework say about charset, syntax, length of a space name?

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#906]
We could have trouble if a consumer uses a space name that the provider does not allow.

**Comment by clubanderson** [comment]
needs some further investigation.  Please update with your findings based on the providers we plan to support.

**Comment by effi-ofer** [comment]
I vote that we declare space names to be defined as kubernetes object names with their associated charset and length. https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#:~:text=This%20means%20the%20name%20must,no%20more%20than%20253%20characters In the case some specific provider supports a subset of what we allow, it will be up to the user to ensure that the space name fulfils those requirements or otherwise an error will be returned.

**Comment by ezrasilvera** [comment]
Why do you think that's an issue?  The user will get an error with the specific error message of the provider. What's the difference from someone trying to create a Kind cluster or a KCP workspace with illegal names ?

**Comment by effi-ofer** [comment]
@MikeSpreitzer can we close this one with the conclusion that it is up to the user to ensure that the space name fulfils the requirements of the provider or otherwise an error will be returned.

**Comment by ezrasilvera** [comment]
@effi-ofer I agree with this approach for our milestone. I suggest we just move this to backlog instead of closing.

**Comment by MikeSpreitzer** [comment]
Moot
