### ISSUE TITLE
bug: release menu is absent in some cases

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#985]
### Describe the bug

For *some*, _not_ all, of the website pages, the release menu does not appear when the selected release is `main`.  Contrast the two attached images of the syncer doc page.  The same thing happens for the "extended example" page.  It does NOT happen on the "details" page.

<img width="1010" alt="Screenshot 2023-09-11 at 5 51 38 PM" src="https://github.com/kubestellar/kubestellar/assets/14296719/64f80077-7735-4a15-b843-ee855e283e08">

vs.

<img width="1011" alt="Screenshot 2023-09-11 at 5 51 27 PM" src="https://github.com/kubestellar/kubestellar/assets/14296719/d626fc79-44bc-4c92-af56-ed0d795d1eb3">

### Steps To Reproduce

See above

### Expected Behavior

I expected to always see the release menu.

**Comment by MikeSpreitzer** [comment]
The problem _is_ on the quickstart page.

**Comment by clubanderson** [comment]
this is only happening in 'main' on pages that have docs-ecutable metadata on the top.  Opened an issue with 'mike' - they closed it stating it is theme related.  I am chasing down the 'material' theme folks next.  The dropdown is in the html DOM.  The behavior of removing the dropdown happens when you scroll down any of our pages.  It seems that the metadata for the 'main' branch docs-ecutable pages is causing this "scroll down" effect on default load.  I am researching a solution.

**Comment by clubanderson** [comment]
Fixed. Required packages had extra open and close code blocks in the new WSL Linux section. I am going to have another swipe at the formatting of this specific section, but for now this issue should be fixed.
