### ISSUE TITLE
feature:  Document troubleshooting steps

### ISSUE THREAD

**Issue by pdettori** [kubestellar/kubestellar#998]
### Feature Description

We need to provide steps to help users to troubleshoot. For example,  the workload does not get delivered to the WEC. We need to document steps such as:

1. check if the Syncer pod is running on the WEC
2. check its log for errors,
3. Check if the workload has been copied on the Mailbox workspace
4.  Check if controller X is running and logs has errors
5.  etc. etc.

### Proposed Solution

TBD

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by KPRoche** [comment]
[copied over from issue #1023 at request of @clubanderson ]

OK, an update on basic installation flow process which I am figuring out

- install prerequisites as listed in quickstart page
- install release 0.11 of kcp for your language/architecture and add to $PATH 
    - download from https://github.com/kcp-dev/kcp/releases/tag/v0.11.0
    - expand files
    - add directories to $PATH
- install stable release of kubestellar
    - download from https://github.com/kubestellar/kubestellar/releases
    - expand file
    - add directory to path
- now you can follow instructions for running bare or using kubectl kubestellar deploy into a cluster
    - **NOTE:** if running bare, starting kcp will create the .kcp folder holding admin.kubeconfig as a subfolder of whatever folder you are in when you issue the command
    - in theory, using **kubectl kubestellar deploy** command (with necessary flags and options) will deploy all the core components to either a kind cluster or (if flag is set) an openshift cluster.
    (_I have not succeeded in getting that deploy to work yet_)
    
#### followup few hours later

the kubestellar deploy was failing because of a bad kubeconfig context. Mike helped me reset it to an appropriate one, and I apparently succeeded in using the command 
**but** 

- it wouldn't respond properly to the commands to get its kubeconfig files, 
- nor to a delete command (empty kubestellar namespace stuck forever in "terminating" state)
- as of now, this has happened on two Raspberry Pis. 
- On one, I attempted a force-termination of the stuck namespace, and rebooted the pi. Kubectl now times out with a TLS handshake error.
(Looking for advice on how to reset the whole kubernetes space without having to build a new OS image for my pi.)

**Comment by KPRoche** [comment]
Additional note: raspberry Pi #2 was able to successfully terminate with the _helm delete kubestellar_ command. The first one is still in kubernetes limbo.

**Comment by KPRoche** [comment]
One final update -- it appears the microshift install on the first pi is toast. If I launch a kind cluster then the TLS error goes away once it is working. (this separate from the kubestellar cluster not responding to requests)

**Comment by KPRoche** [comment]
Further update -- It apparently just takes a long time for the kubestellar server to really spin up. The one on my second pi (running in the kind context, not the microshift context) has successfully spun up and I could fetch the admin and external kubeconfig files from it.

**Comment by KPRoche** [comment]
And the same has turned out to be true for the first rPi.

So the real problem with the "easy" cluster deployment is determining when the kubestellar server is ready to respond to commands.

**Comment by KPRoche** [comment]
OK, solved one mystery. I'd used a graphical file manager to call the extraction of the tar.gz files for kcp. It did not create all the symbolic links.
  - install release 0.11 of kcp for your language/architecture and add to $PATH
    * download from https://github.com/kcp-dev/kcp/releases/tag/v0.11.0
    * expand files _use the **tar** command line to make sure symlinks are created properly_ <----------
    * add directories to $PATH

**Comment by KPRoche** [comment]
This ties back to https://github.com/kubestellar/kubestellar/pull/1042

**Comment by KPRoche** [comment]
Latest version of my basic install list
 ***On system hosting kubestellar core
- install prerequisites as listed in quickstart page
- install release 0.11 of kcp for your language/architecture and add to $PATH 
    - download from https://github.com/kcp-dev/kcp/releases/tag/v0.11.0
    - expand files -- use tar CLI not GUI to ensure symlinks are created
    - add directories to $PATH
- install stable release of kubestellar
    - download from https://github.com/kubestellar/kubestellar/releases
    - expand file
    - add directory to path
- now you can follow instructions for running bare or using kubectl kubestellar deploy into a cluster
    - Running Bare
      - **NOTE:** if running bare, starting kcp will create the .kcp folder holding admin.kubeconfig as a subfolder of whatever folder you are in when you issue the command
    - Running in a cluster
      - You need to create a cluster with appropriate ingress (link to add)
       - use **kubectl kubestellar deploy** command (with necessary flags and options) will deploy all the core components to either a kind cluster or (if flag is set) an openshift cluster.
       - fetch the external kubeconfig and internal kubeconfig files for the kubestellar server
       - if creating WEC on a different host, modify port control for the server

**Comment by namasl** [comment]
Adding reference to #920, since we seem to be collecting the troubleshooting tips here

**Comment by clubanderson** [comment]
Added troubleshooting label

**Comment by clubanderson** [comment]
@KPRoche can you test the helm chart instead of using manual methods to install the bare or containerized versions.  We need to focus on helm and brew.  Having multiple ways to install our software is making it difficult to focus on priorities.  If you can put a kind cluster on your environment and then load in helm, that would be the best way to help us test.

**Comment by clubanderson** [comment]
please include info from #920
